# The media_network Stack - youtube.com/@KLTechVideos
# Prowlarr - Sonarr - Radarr - Lidarr - Readarr
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest # Change to "latest" for stable
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONTAINER_DIR}Prowlarr\Config:/config
      - ${CONTAINER_DIR}Prowlarr\Backup:/data/Backup
      - ${MEDIA_DIR}Downloads:/data/downloads
    ports:
      - 9697:9696
    restart: unless-stopped
    networks:
      - media_network
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest # Change to "latest" for stable
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONTAINER_DIR}Sonarr/Config:/config
      - ${CONTAINER_DIR}Sonarr/Backup:/data/Backup
      - ${MEDIA_DIR}TV-Shows:/data/tvshows
      - ${MEDIA_DIR}Downloads:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media_network
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONTAINER_DIR}Radarr\Config:/config
      - ${CONTAINER_DIR}Radarr\Backup:/data/Backup
      - ${MEDIA_DIR}Movies:/data/movies
      - ${MEDIA_DIR}Downloads:/data/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media_network
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONTAINER_DIR}Lidarr\Config:/config
      - ${CONTAINER_DIR}Lidarr\Music:/data/musicfolder
      - ${CONTAINER_DIR}Lidarr\Backup:/data/Backup
      - ${MEDIA_DIR}Downloads:/data/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - media_network
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONTAINER_DIR}Readarr\Config:/config
      - ${CONTAINER_DIR}Readarr\Books:/data/books # optional
      - ${MEDIA_DIR}Downloads:/data/downloads # optional
    ports:
      - 8585:8585
    restart: unless-stopped
    networks:
      - media_network
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONTAINER_DIR}Qbittorrent/appdata:/config
      - ${MEDIA_DIR}Downloads:data/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - media_network
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ${CONTAINER_DIR}Jellyfin\Config:/config
      - ${MEDIA_DIR}Movies:/data/movies
      - ${MEDIA_DIR}TV-Shows:/data/tv-shows
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
networks:
  media_network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.25.0.0/16
          gateway: 173.25.0.1